# Generated by Django 5.0.4 on 2024-06-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
